### ISSUE TITLE
Can't load NIF library in the default phoenix debian docker image: undefined symbol: ucol_strcollIter_67

### ISSUE THREAD

**Issue by linusdm** [elixir-cldr/cldr_collation#6]
I’m trying to add ex_cldr_collation as a dependency to a standard phoenix application. The problem arises when building and running the application in a docker container. These are the steps to reproduce:
- `mix phx.new my_app` (version `1.7.0-rc.3`)
- add dependency to `ex_cldr_collation` in `mix.exs` (version `0.7.1`)
- `mix phx.gen.release --docker` to generate the default Dockerfile
- modify Dockerfile and add apt package `libicu-dev` to the _builder_ image, as explained in [the docs](https://github.com/elixir-cldr/cldr_collation#installation-on-linux) (~~`pkgconf` is not really reaquired I think~~ **this was a wrong assumption, read ahead in the comments**)
- `docker build . -t my_app`
- `docker run -it my_app`

When the image starts the phoenix application, I get this error:

```elixir
  crasher:
    initial call: application_master:init/4
    pid: <0.2044.0>
    registered_name: []
    exception exit: {{shutdown,
                      {failed_to_start_child,kernel_safe_sup,
                       {on_load_function_failed,'Elixir.Cldr.Collation',
                        {{badmatch,
                          {error,
                           {load_failed,
                            "Failed to load NIF library: '/app/lib/ex_cldr_collation-0.7.1/priv/ucol.so: undefined symbol: ucol_strcollIter_67'"}}},
                         [{'Elixir.Cldr.Collation',init,0,
                           [{file,"lib/cldr_collation.ex"},{line,20}]},
                          {init,'-run_on_load_handlers/2-fun-0-',1,[]}]}}}},
                     {kernel,start,[normal,[]]}}
      in function  application_master:init/4 (application_master.erl, line 142)
  ...
```

Adding the debian package [libicu67](https://packages.debian.org/bullseye/libicu67) to the _runner_ image doesn't solve the problem. This is unexpected though: the symbol `ucol_strcollIter_67` _is_ found in the shared object at `/usr/lib/x86_64-linux-gnu/libicui18n.so` (which [comes with said debian package](https://packages.debian.org/bullseye/amd64/libicu67/filelist)).
I checked by running `nm -D --demangle libicui18n.so` in the docker container (after installing `binutils` to get the `nm` utility), where the sybol shows up with a `T` marker, which should indicate it's present in the so file (that's an assumption, because I don't really know what I'm doing here 🤷 ).

I don't know how this should work, but is there something missing to tell elixir to also look into this other so file when loading NIF's? I'd be surprised, because it seems to work on other distro's without any problems.

**Comment by kipcole9** [comment]
I'm am absolutely not good debugging Linux linking issues.  But it does (to this idiot) looking like the NIF is linked to the wrong libraries.

In the Makefile there is:
```
ifeq ($(UNAME_SYS), Darwin)
	ICU_CFLAGS = -I$(BASEDIR)/c_src/platform/osx/icu
	ICU_LIBS = -lpthread -lm -licucore -lstdc++
else
	ICU_CFLAGS = $(shell pkg-config --cflags icu-uc icu-io)
	ICU_LIBS = $(shell pkg-config --libs icu-uc icu-io)
endif
```
So if for some reason the NIF is built against something else there could be an issue (I know how imprecise this sounds).  

~The only thing I can think of for now is to install the `icu` package for the runner and the builder for now since that guarantees a set of matched libraries (both `-dev` and runtime parts).  If that works then at least there is something to go on~. And maybe worth running `pkg-config --libs icu-uc icu-io` just to see if at least it resolves the libs to link to?

**Comment by linusdm** [comment]
I'm failing to grasp what exactly you mean with "install the `icu` pakage", because as far as I can see, there is no literal `icu` package in the [debian package repository](https://packages.debian.org/search?suite=bullseye&searchon=names&keywords=icu). The closest I get is the `libicu67` package [here](https://packages.debian.org/bullseye/libicu67). Installing the [`libicu-dev`](https://packages.debian.org/bullseye/libicu-dev) package in the _runner_ also doesn't solve it.

running `pkg-config` yields this:
```
nobody@0ecec4d83a92:/app$ pkg-config --libs icu-uc icu-io
-licuio -licui18n -licuuc -licudata
```
Which is correct, I think.

> I'm am absolutely not good debugging Linux linking issues.

Don't be fooled by my name that I am any better at this :P

**Comment by kipcole9** [comment]
We must have been writing at the same time - I've edited my answer to reflect your reality (since my reality was a false one based on my misunderstanding almost everything about what I was reading).

Best I can tell you are doing everything right (not a resounding endorsement though given my lack of knowledge)!

**Comment by kipcole9** [comment]
I'll happily power up a Debian instance on DO and try it out myself but I won't be able to do that until the weekend.  I don't suppose there is a paths conflict and there are somehow multiple library versions lying around?  Its a stretch I admit.

**Comment by linusdm** [comment]
You can easily reproduce locally because it's a docker build (I hope that's clear from the steps to reproduce above). I also just do this locally, only depending on docker being available on my machine.

I only installed the listed dependencies as described in the Dockerfile. If there is any conflict, I'd be amazed, but I wouldn't know, to be honest. The only dependencies are found [here](https://github.com/phoenixframework/phoenix/blob/master/priv/templates/phx.gen.release/Dockerfile.eex#L24) and [here](https://github.com/phoenixframework/phoenix/blob/master/priv/templates/phx.gen.release/Dockerfile.eex#L70).

No worries regarding any timing. I can live without collation for a while :) I'd be happy to chip in if needed.

**Comment by jswanner** [comment]
@linusdm, out of curiosity, did you try adding pkgconf to the builder and runner images?

I added ex_cldr_collation to a project 2 weeks ago, and it's deployed to fly.io. At first I tried only adding libicu-dev and pkgconf to the builder image, when that failed to deploy I added both to the runner image and it's been fine since. 

In case it's of any help, these are the images I'm using:

BUILDER_IMAGE="hexpm/elixir:1.14.0-erlang-25.0.4-debian-bullseye-20220801-slim"
RUNNER_IMAGE="debian:bullseye-20220801-slim"

**Comment by linusdm** [comment]
@jswanner that was an excellent tip to start fiddling with the installed apt dependencies again.

> modify Dockerfile and add apt package libicu-dev to the builder image, as explained in [the docs](https://github.com/elixir-cldr/cldr_collation#installation-on-linux) (pkgconf is not really reaquired I think)

As it turns out, the `pkgconf` dependency in the builder image _does_ make a difference! I was mislead by thinking that when everything could be built, at least the set of dependencies of the docker build step was ok. But that's not true. Apparently you can build without pkgconf without an error, but then hit the error I've described above.

I'm curious if the build step could be halted if pkgconf is not available when running the Makefile. The variable `ICU_LIBS` must be empty when running (g)cc, but everything goes through without an error.

I think I have to catalog this as a user-error, because the dependency on pkgconf is beautifully described in the docs :-)

Btw, in this specific setup (default phoenix Dockerfile based on debian) the only required dependency for the _runner_ image seems to be `libicu67` (`pkgconf` is _not_ required in the runner step, as far as I can see).

**Comment by linusdm** [comment]
I've inspected the compile output, and it's obvious now that this couldn't have worked without pkgconf at compile-time:

```
==> ex_cldr_collation
Eshell V13.1.4  (abort with ^G)
1> make: pkg-config: No such file or directory
make: pkg-config: No such file or directory
cc c_src/ucol.o -shared -L/usr/local/lib/erlang/usr/lib -lei  -o ./priv/ucol.so
Compiling 3 files (.ex)

08:58:39.720 [warning] The on_load function for module Elixir.Cldr.Collation returned:
{{:badmatch,
  {:error,
   {:load_failed,
    'Failed to load NIF library: \'/app/_build/prod/lib/ex_cldr_collation/priv/ucol.so: undefined symbol: ucol_strcollIter_67\''}}},
 [
   {Cldr.Collation, :init, 0, [file: 'lib/cldr_collation.ex', line: 20]},
   {:code_server, :"-handle_on_load/5-fun-0-", 1,
    [file: 'code_server.erl', line: 1317]}
 ]}


08:58:39.719 [error] Process #PID<0.3310.0> raised an exception
** (MatchError) no match of right hand side value: {:error, {:load_failed, 'Failed to load NIF library: \'/app/_build/prod/lib/ex_cldr_collation/priv/ucol.so: undefined symbol: ucol_strcollIter_67\''}}
    lib/cldr_collation.ex:20: Cldr.Collation.init/0
    (kernel 8.5.3) code_server.erl:1317: anonymous fn/1 in :code_server.handle_on_load/5
Generated ex_cldr_collation app
```

But although this fails very obviously, the compilation just goes through as if nothing happened. Should compilation fail in this situation? I want to prevent someone in the future doing something similar, trying to be "smart" like I did.

**Comment by kipcole9** [comment]
@linusdm, I've pushed [a commit](https://github.com/elixir-cldr/cldr_collation/commit/ec7f267167fade8f798c6bf9e7f02b231dc770e0) that causes the `Makefile` to fail if `ICU_FLAGS` or `ICU_LIBS` is not set. It would not be set if `pkg-config` wasn't installed or there was some other error.

Would you consider trying this version from GitHub (`{:ex_cldr_collation, github: "elixir-cldr/cldr_collation"}` deps configuration) and running it with your original docker file to confirm it correctly errors?

**Comment by linusdm** [comment]
I made a suggestion on top of your changes: https://github.com/elixir-cldr/cldr_collation/pull/7
Fails much better now (with the suggested changes), thanks!
